### ISSUE TITLE
ask about project proposal page expectations

### ISSUE THREAD

**Issue by CAMPSMITH** [CAMPSMITH/StableOps#7]

**Comment by quintinbland** [comment]
Project Proposal and Outline
Before you start writing any code, your group should outline the scope and purpose of your project. This will help provide direction and safeguard against scope creep. Your should format the proposal and outline as a brief summary of your interests and intent. Make sure to include:

The kind of data you’d like to work with and the field you’re interested in (e.g., trading, quantitative analysis)
The questions you’ll ask of the data
Possible source for the data
It should look something like this:

(Rough Draft)
The aim of our project is to uncover patterns in stable coins. We’ll examine relationships between stable coins pegged to USD and coins pegged to other foreign currencies. We'll analyze stable coin volatility, search for potential arbitrage opportunities, and review other related questions that will derive from the data.

**Comment by CAMPSMITH** [comment]
question raised

**Comment by CAMPSMITH** [comment]
done
